export const ERROR_CODES = {
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  CATEGORY_ALREADY_EXISTS: "CATEGORY_ALREADY_EXISTS",
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  CATEGORY_NOT_EMPTY: "CATEGORY_NOT_EMPTY",

  MENU_ITEM_ALREADY_EXISTS: "MENU_ITEM_ALREADY_EXISTS",
  MENU_ITEM_NOT_FOUND: "MENU_ITEM_NOT_FOUND",

  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  CONFLICT: "CONFLICT",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  CART_ITEM_NOT_FOUND: "CART_ITEM_NOT_FOUND",
  CART_NOT_FOUND: "CART_NOT_FOUND",
  MENU_ITEM_UNAVAILABLE: "MENU_ITEM_UNAVAILABLE",

  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
} as const;